### ISSUE TITLE
Autocompletion errors in nengo-gui on win 10 x64 with python 3.7

### ISSUE THREAD

**Issue by shumtravi** [nengo/nengo-gui#1035]
When i work with nengo-gui it works nice except autocompletion. And i got this errors:

```
ERROR:nengo_gui.server:Error response
Traceback (most recent call last):
  File "c:\users\dmitry\appdata\local\conda\conda\envs\ml-p37-nengo-tf\lib\site-packages\nengo_gui\server.py", line 412, in do_GET
    self.http_GET()
  File "c:\users\dmitry\appdata\local\conda\conda\envs\ml-p37-nengo-tf\lib\site-packages\nengo_gui\guibackend.py", line 137, in http_GET
    server.HttpWsRequestHandler.http_GET(self)
  File "c:\users\dmitry\appdata\local\conda\conda\envs\ml-p37-nengo-tf\lib\site-packages\nengo_gui\server.py", line 428, in http_GET
    response = getattr(self, command)()
  File "c:\users\dmitry\appdata\local\conda\conda\envs\ml-p37-nengo-tf\lib\site-packages\nengo_gui\guibackend.py", line 86, in auth_checked
    return fn(inst)
  File "c:\users\dmitry\appdata\local\conda\conda\envs\ml-p37-nengo-tf\lib\site-packages\nengo_gui\guibackend.py", line 218, in complete
    self.db['filename'])
  File "c:\users\dmitry\appdata\local\conda\conda\envs\ml-p37-nengo-tf\lib\site-packages\nengo_gui\completion.py", line 22, in get_completions
    script = Script(code, line, column, path=path)
TypeError: __init__() takes from 1 to 2 positional arguments but 4 positional arguments (and 1 keyword-only argument) were given
```

Windows10 Pro x64 10.0.19041

Nengo, nengo-gui, nengo-dl installed in separate env. with python 3.7 using pip. Here is "pip list" output for nengo env:

```
Package                Version
---------------------- -------------------
absl-py                0.11.0
astunparse             1.6.3
cachetools             4.2.1
certifi                2020.12.5
chardet                4.0.0
flatbuffers            1.12
gast                   0.3.3
google-auth            1.27.0
google-auth-oauthlib   0.4.2
google-pasta           0.2.0
grpcio                 1.32.0
h5py                   2.10.0
idna                   2.10
importlib-metadata     3.7.0
jedi                   0.18.0
Jinja2                 2.11.3
joblib                 1.0.1
Keras-Preprocessing    1.1.2
Markdown               3.3.4
MarkupSafe             1.1.1
nengo                  3.0.0
nengo-dl               3.4.0
nengo-gui              0.4.7
numpy                  1.19.5
oauthlib               3.1.0
opt-einsum             3.3.0
packaging              20.9
parso                  0.8.1
pip                    21.0.1
progressbar2           3.53.1
protobuf               3.15.3
pyasn1                 0.4.8
pyasn1-modules         0.2.8
pyparsing              2.4.7
python-utils           2.5.6
requests               2.25.1
requests-oauthlib      1.3.0
rsa                    4.7.2
scikit-learn           0.24.1
scipy                  1.6.1
setuptools             52.0.0.post20210125
six                    1.15.0
tensorboard            2.4.1
tensorboard-plugin-wit 1.8.0
tensorflow             2.4.1
tensorflow-estimator   2.4.0
termcolor              1.1.0
threadpoolctl          2.1.0
typing-extensions      3.7.4.3
urllib3                1.26.3
Werkzeug               1.0.1
wheel                  0.36.2
wincertstore           0.2
wrapt                  1.12.1
zipp                   3.4.0

```

**Comment by Tobias-Fischer** [comment]
Hi @shumtravi - see https://github.com/nengo/nengo-gui/pull/1038
