### ISSUE TITLE
Installation into a directory with a unicode character

### ISSUE THREAD

**Issue by cchan987** [nengo/nengo-gui#139]

**Comment by jgosmann** [comment]
Windows 7, Python 2.7: not working

```
C:\Users\jgosmann>nengo_gui
C:\Users\jgosmann\crazy òⁿ\lib\site-packages\IPython\nbformat\current.py:19: UserWarning: IPython.nbformat.curre

- use IPython.nbformat for read/write/validate public API
- use IPython.nbformat.vX directly to composing notebooks of a particular version

  """)
:0: FutureWarning: IPython widgets are experimental and may change in the future.
Starting nengo_gui server at http://localhost:8080
(<type 'exceptions.UnicodeDecodeError'>, UnicodeDecodeError('ascii', 'Traceback (most recent call last):\n  File
n\\crazy \x95\xfc\\lib\\site-packages\\nengo_gui-0.1.5.dev0-py2.7.egg\\nengo_gui\\swi.py", line 276, in handle_r
etattr(self, command)(*args[1:], **db)\n  File "C:\\Users\\jgosmann\\crazy \x95\xfc\\lib\\site-packages\\nengo_g
egg\\nengo_gui\\server.py", line 88, in swi\n    components = page.create_javascript()\n  File "C:\\Users\\jgosm
\lib\\site-packages\\nengo_gui-0.1.5.dev0-py2.7.egg\\nengo_gui\\page.py", line 295, in create_javascript\n    fn
ilename)\n  File "C:\\Users\\jgosmann\\crazy \x95\xfc\\lib\\json\\__init__.py", line 243, in dumps\n    return _
de(obj)\n  File "C:\\Users\\jgosmann\\crazy \x95\xfc\\lib\\json\\encoder.py", line 201, in encode\n    return en
i(o)\nUnicodeDecodeError: \'utf8\' codec can\'t decode byte 0x95 in position 6: invalid start byte\n</pre></body
ordinal not in range(128)'), ['__class__', '__delattr__', '__dict__', '__doc__', '__format__', '__getattribute__
_getslice__', '__hash__', '__init__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__se
__', '__str__', '__subclasshook__', '__unicode__', 'args', 'encoding', 'end', 'message', 'object', 'reason', 'st
----------------------------------------
Exception happened during processing of request from ('127.0.0.1', 49451)
Traceback (most recent call last):
  File "C:\Users\jgosmann\crazy òⁿ\lib\SocketServer.py", line 599, in process_request_thread
    self.finish_request(request, client_address)
  File "C:\Users\jgosmann\crazy òⁿ\lib\SocketServer.py", line 334, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "C:\Users\jgosmann\crazy òⁿ\lib\SocketServer.py", line 655, in __init__
    self.handle()
  File "C:\Users\jgosmann\crazy òⁿ\lib\BaseHTTPServer.py", line 340, in handle
    self.handle_one_request()
  File "C:\Users\jgosmann\crazy òⁿ\lib\BaseHTTPServer.py", line 328, in handle_one_request
    method()
  File "C:\Users\jgosmann\crazy òⁿ\lib\site-packages\nengo_gui-0.1.5.dev0-py2.7.egg\nengo_gui\swi.py", line 210,
    self.handle_request(args, db)
  File "C:\Users\jgosmann\crazy òⁿ\lib\site-packages\nengo_gui-0.1.5.dev0-py2.7.egg\nengo_gui\swi.py", line 287,
    b = ("%s</pre></body></html>" % text).encode("utf-8")
UnicodeDecodeError: 'ascii' codec can't decode byte 0x95 in position 67: ordinal not in range(128)
----------------------------------------
```

**Comment by tcstewar** [comment]
This should be checked again to see whether some of the refactoring that has happened has changed the state of this bug.

**Comment by krisfrenette** [comment]
Verified that this is working as expected. We are no longer supporting Python 2 so validation for Python 2 is no longer needed.
