### ISSUE TITLE
Bad exiting behaviour

### ISSUE THREAD

**Issue by celiasmith** [nengo/nengo-gui#14]
When I close the window on a mac, the server gets angry:

Traceback (most recent call last):
  File "/Users/celiasmi/Documents/nengo/nengo_viz/nengo_viz/swi.py", line 202, in handle_ws_request
Traceback (most recent call last):
Traceback (most recent call last):
  File "/Users/celiasmi/Documents/nengo/nengo_viz/nengo_viz/swi.py", line 202, in handle_ws_request
Traceback (most recent call last):
  File "/Users/celiasmi/Documents/nengo/nengo_viz/nengo_viz/swi.py", line 202, in handle_ws_request
  File "/Users/celiasmi/Documents/nengo/nengo_viz/nengo_viz/swi.py", line 202, in handle_ws_request
Traceback (most recent call last):
  File "/Users/celiasmi/Documents/nengo/nengo_viz/nengo_viz/swi.py", line 202, in handle_ws_request
    getattr(self, command)(_[client] + args[1:], *_db)
    getattr(self, command)(_[client] + args[1:], *_db)
    getattr(self, command)(_[client] + args[1:], *_db)
  File "/Users/celiasmi/Documents/nengo/nengo_viz/nengo_viz/server.py", line 39, in ws_viz_component
  File "/Users/celiasmi/Documents/nengo/nengo_viz/nengo_viz/server.py", line 39, in ws_viz_component
    getattr(self, command)(_[client] + args[1:], *_db)
  File "/Users/celiasmi/Documents/nengo/nengo_viz/nengo_viz/server.py", line 39, in ws_viz_component
  File "/Users/celiasmi/Documents/nengo/nengo_viz/nengo_viz/server.py", line 39, in ws_viz_component
    msg = client.read()
  File "/Users/celiasmi/Documents/nengo/nengo_viz/nengo_viz/swi.py", line 461, in read
    assert(0x1 == (0xF & data[0]))
    msg = client.read()
    msg = client.read()
  File "/Users/celiasmi/Documents/nengo/nengo_viz/nengo_viz/swi.py", line 461, in read
AssertionError
  File "/Users/celiasmi/Documents/nengo/nengo_viz/nengo_viz/swi.py", line 461, in read
    getattr(self, command)(_[client] + args[1:], *_db)
  File "/Users/celiasmi/Documents/nengo/nengo_viz/nengo_viz/server.py", line 39, in ws_viz_component
    msg = client.read()
  File "/Users/celiasmi/Documents/nengo/nengo_viz/nengo_viz/swi.py", line 461, in read
    assert(0x1 == (0xF & data[0]))
AssertionError
    msg = client.read()
  File "/Users/celiasmi/Documents/nengo/nengo_viz/nengo_viz/swi.py", line 461, in read
    assert(0x1 == (0xF & data[0]))
    assert(0x1 == (0xF & data[0]))
AssertionError
    assert(0x1 == (0xF & data[0]))
AssertionError
AssertionError

**Comment by tcstewar** [comment]
You get that sort of error on any operating system.  It should definitely get cleaned up, though.

**Comment by tcstewar** [comment]
Exiting behaviour has been much improved
