### ISSUE TITLE
Jedi autocompletion throws lots of errors

### ISSUE THREAD

**Issue by Seanny123** [nengo/nengo-gui#962]
When I'm typing code into the Nengo GUI and it doesn't compile, it still gets passed to Jedi, which causes a bunch of errors like:

```
ERROR:nengo_gui.server:Error response
Traceback (most recent call last):
  File "/home/saubin/git/nengo_gui/nengo_gui/server.py", line 400, in do_GET
    self.http_GET()
  File "/home/saubin/git/nengo_gui/nengo_gui/server.py", line 416, in http_GET
    response = getattr(self, command)()
  File "/home/saubin/git/nengo_gui/nengo_gui/guibackend.py", line 84, in auth_checked
    return fn(inst)
  File "/home/saubin/git/nengo_gui/nengo_gui/guibackend.py", line 199, in complete
    self.db['filename'])
  File "/home/saubin/git/nengo_gui/nengo_gui/completion.py", line 19, in get_completions
    return script.completions()
  File "/usr/local/lib/python3.6/dist-packages/jedi/api/__init__.py", line 174, in completions
    completions = completion.completions()
  File "/usr/local/lib/python3.6/dist-packages/jedi/api/completion.py", line 97, in completions
    completion_names = self._get_context_completions()
  File "/usr/local/lib/python3.6/dist-packages/jedi/api/completion.py", line 172, in _get_context_completions
    completion_names = list(self._get_keyword_completion_names(allowed_keywords))
  File "/usr/local/lib/python3.6/dist-packages/jedi/api/completion.py", line 209, in _get_keyword_completion_names
    yield keywords.KeywordName(self._evaluator, k)
  File "/usr/local/lib/python3.6/dist-packages/jedi/api/keywords.py", line 28, in __init__
    self.parent_context = evaluator.builtins_module
  File "/usr/local/lib/python3.6/dist-packages/jedi/evaluate/cache.py", line 40, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/jedi/evaluate/__init__.py", line 115, in builtins_module
    return compiled.get_special_object(self, u'BUILTINS')
  File "/usr/local/lib/python3.6/dist-packages/jedi/evaluate/compiled/__init__.py", line 27, in get_special_object
    evaluator.compiled_subprocess.get_special_object(identifier)
  File "/usr/local/lib/python3.6/dist-packages/jedi/evaluate/compiled/context.py", line 458, in create_from_access_path
    for name, access in access_path.accesses:
AttributeError: 'NoneType' object has no attribute 'accesses'
ERROR:nengo_gui.server:Error response
Traceback (most recent call last):
  File "/home/saubin/git/nengo_gui/nengo_gui/server.py", line 400, in do_GET
    self.http_GET()
  File "/home/saubin/git/nengo_gui/nengo_gui/server.py", line 416, in http_GET
    response = getattr(self, command)()
  File "/home/saubin/git/nengo_gui/nengo_gui/guibackend.py", line 84, in auth_checked
    return fn(inst)
  File "/home/saubin/git/nengo_gui/nengo_gui/guibackend.py", line 199, in complete
    self.db['filename'])
  File "/home/saubin/git/nengo_gui/nengo_gui/completion.py", line 19, in get_completions
    return script.completions()
  File "/usr/local/lib/python3.6/dist-packages/jedi/api/__init__.py", line 174, in completions
    completions = completion.completions()
  File "/usr/local/lib/python3.6/dist-packages/jedi/api/completion.py", line 97, in completions
    completion_names = self._get_context_completions()
  File "/usr/local/lib/python3.6/dist-packages/jedi/api/completion.py", line 198, in _get_context_completions
    completion_names += self._global_completions()
  File "/usr/local/lib/python3.6/dist-packages/jedi/api/completion.py", line 223, in _global_completions
    completion_names += filter.values()
  File "/usr/local/lib/python3.6/dist-packages/jedi/evaluate/compiled/context.py", line 348, in values
    needs_type_completions, dir_infos = self._compiled_object.access_handle.get_dir_infos()
TypeError: 'NoneType' object is not iterable
```

Is this debug info I'm just supposed to ignore?

**Comment by jgosmann** [comment]
Can't reproduce. When I try code with syntax errors, the auto-completion keeps working for me. Can you provide more details?

**Comment by Seanny123** [comment]
It happens constantly on my Windows 10 machine while typing nengo-spa code. I realize this isn't exactly a minimally reproducible example, but at least it will be easy to show you on Monday?

**Comment by Seanny123** [comment]
Whelp, it stopped happening now and I can't make it happen, so I guess I'll close the issue?

**Comment by jgosmann** [comment]
Or any chance you've updated Jedi itself?

**Comment by Seanny123** [comment]
Magically just stopped happening. I can guarantee with 90% confidence I
didn't change my environment at all.

**Comment by jgosmann** [comment]
@Seanny123 Can you test whether #977 solves this problem? (If you are able to reproduce this. Try typing fast.)

**Comment by Seanny123** [comment]
I commented in #977 but I thought I would here that I still get the same error.

**Comment by jgosmann** [comment]
Can you show me on your computer sometime?

**Comment by Seanny123** [comment]
Well, I don't get it anymore, despite typing frantically on the slow lab laptop which usually most reliably created these errors. Consequently, I'm going to close it for now.
