### ISSUE TITLE
Nengo gui frequently stuck at gear icon without actually building anything

### ISSUE THREAD

**Issue by aleksejs-fomins** [nengo/nengo-gui#970]
Usually have errors in terminal. In this particular case the terminal output is as follows

>>nengo
Starting nengo server accessible at:
  http://localhost:8080/?token=b89cf8b30109886802dca2d9fac3cb009b10c0c9133171ad
Exception in thread Thread-78:
Traceback (most recent call last):
  File "/opt/anaconda3/envs/py36qt5/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/opt/anaconda3/envs/py36qt5/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/anaconda3/envs/py36qt5/lib/python3.6/site-packages/nengo_gui/page.py", line 526, in runner
    self.build()
  File "/opt/anaconda3/envs/py36qt5/lib/python3.6/site-packages/nengo_gui/page.py", line 458, in build
    c.add_nengo_objects(self)
  File "/opt/anaconda3/envs/py36qt5/lib/python3.6/site-packages/nengo_gui/components/pointer.py", line 61, in add_nengo_objects
    self.conn2 = nengo.Connection(self.node, output, synapse=0.01)
  File "/opt/anaconda3/envs/py36qt5/lib/python3.6/site-packages/nengo/base.py", line 35, in __call__
    inst.__init__(*args, **kwargs)
  File "/opt/anaconda3/envs/py36qt5/lib/python3.6/site-packages/nengo/connection.py", line 430, in __init__
    self.post = post
  File "/opt/anaconda3/envs/py36qt5/lib/python3.6/site-packages/nengo/base.py", line 106, in __setattr__
    super(NengoObject, self).__setattr__(name, val)
  File "/opt/anaconda3/envs/py36qt5/lib/python3.6/site-packages/nengo/config.py", line 456, in __setattr__
    reraise(exc_info[0], exc_info[1], None)
  File "/opt/anaconda3/envs/py36qt5/lib/python3.6/site-packages/nengo/utils/compat.py", line 96, in reraise
    raise value.with_traceback(tb)
nengo.exceptions.ValidationError: Connection.post: '<SpaOutput<Node> (unlabeled) at 0x7fb485364d68>' must have size_in > 0.

**Comment by jgosmann** [comment]
I think the problem here is that the vocabulary is initially empty and an empty cleanup memory cannot be created (or rather not connected to). This should be addressed by forthcoming changes discussed in [this comment](https://github.com/nengo/nengo-spa/pull/171#issuecomment-395085499). Essentially users will be forced to provide the list of keys the cleanup memory can clean up to.

**Comment by jgosmann** [comment]
While my previous comment describes an important issue too, the actual problem here is that the Semantic Pointer plots in the GUI allow to set Semantic Pointers values and connect for the modules to do so. However, not all `spa.Transcode` modules allow an input. Adding a plot for a transcode module that doesn't allow for an input leads to this error.
